Repository Jordan-Teaching-Technologist/Team-B, pull requests merged in 2024-04, with the labels that each got.

#144 feat: use object pool to manage skill balls
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Gamemanager/SkillBallPoolManager.cs
  Assets/Scripts/Gamemanager/SkillBallPoolManager.cs.meta
  Assets/Scripts/Player/Cheese/CheeseSkill/GetSkill.cs
  Assets/Scripts/UIEvents/FightManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#147 add more skill ball points
  Assets/Scenes/GameScene.unity
  Assets/Scripts/UIEvents/FightManager.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
Labels: bug

#148 138 integrate smell bomb skill
  Assets/.DS_Store
  Assets/Materials/Skill_Icon/smellBomb.png
  Assets/Materials/Skill_Icon/smellBomb.png.meta
  Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
  Assets/Resources/Cheese.prefab
  Assets/Resources/SmellSkillBall.prefab
  Assets/Resources/SmellSkillBall.prefab.meta
  Assets/Resources/UI/CheeseFightUI.prefab
  Assets/Resources/UI/HumanFightUI.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Gamemanager/SkillBallPoolManager.cs
  Assets/Scripts/Gamemanager/SkillBallPoolManager.cs.meta
  Assets/Scripts/Player/Cheese/CheeseSkill/GetSkill.cs
  Assets/Scripts/Player/Cheese/CheeseSkill/SmellBombSkill.cs
  Assets/Scripts/Player/Cheese/CheeseThirdPerson.cs
  Assets/Scripts/UIEvents/CheeseFightUI.cs
  Assets/Scripts/UIEvents/FightManager.cs
  Assets/Scripts/UIEvents/HumanFightUI.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#151 Add new button that return to the room
  Assets/Resources/UI/LossUI.prefab
  Assets/Resources/UI/WinUI.prefab
  Assets/Scripts/UIEvents/FightManager.cs
  Assets/Scripts/UIEvents/LossUI.cs
  Assets/Scripts/UIEvents/WinUI.cs
Labels: bug, enhancement

#163 use green to show the ready players
  Assets/Resources/UI/LossUI 1.prefab
  Assets/Resources/UI/LossUI 1.prefab.meta
  Assets/Resources/UI/RoomUI.prefab
  Assets/Scripts/UIEvents/RespawnUI.cs
  Assets/Scripts/UIEvents/RoomItem.cs
Labels: bug

#164 162 adjust model
  Assets/Animations/Door.anim
  Assets/Animations/Door.anim.meta
  Assets/Animations/Door1.controller
  Assets/Animations/Door2.controller
  Assets/Animations/Door2.controller.meta
  Assets/Animations/DoorInverse.anim
  Assets/Animations/DoorInverse.anim.meta
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Environment/DoorInteraction.cs
  Assets/Scripts/Environment/DoorInteractionWithoutSmell.cs
Labels: bug, enhancement

#170 139 minimap image update
  Assets/Resources/Images/1st.png
  Assets/Resources/Images/mapsrc.png
  Assets/Resources/Images/mapsrc.png.meta
  Assets/Resources/UI/CheeseFightUI.prefab
  Assets/Resources/UI/HumanFightUI.prefab
  Assets/Scenes/GameScene.unity
  Assets/Scenes/GameScene/Lightmap-0_comp_light.exr.meta
  Assets/Scripts/Gamemanager/MiniMapController.cs
  Assets/Scripts/UIEvents/LossUI.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
Labels: enhancement

#171 fix start button problem
  Assets/Scripts/UIEvents/LobbyUI.cs
  Assets/Scripts/UIEvents/LoginUI.cs
  Assets/Scripts/UIEvents/LossUI.cs
  Assets/Scripts/UIEvents/RoomUI.cs
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Bangers SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Oswald Bold SDF.asset
Labels: bug
